### PR TITLE
release v0.2.0-canary.2

### PR DESCRIPTION
**Pull request by a-catgirl-dev**
~~this pull request is like the v0.2.0 release stuff you already know the drill~~

~~except we don't speak about the drill around these parts...~~

canary 2 now

### CODE REVIEW

**Comment by pparaxan** [comment]
mo

**Comment by a-catgirl-dev** [comment]
go away

**Comment by pparaxan** [comment]
> go away

moo

**Comment by a-catgirl-dev** [comment]
nya

**Comment by pparaxan** [comment]
image

**Comment by a-catgirl-dev** [comment]
no

**Comment by a-catgirl-dev** [comment]
(marking as ready for review so i know if im gonna have to set aside 51 years to fix merge conflicts)

**Comment by a-catgirl-dev** [comment]
HOW no merge conflicts im actually hacking im using dream's plugin to increase my luck by 2^15%

**Comment by pparaxan** [comment]
image

**Comment by a-catgirl-dev** [comment]
manually merged cause github is a pain

**Pull request closed without merging**
